apiVersion: v1
kind: Deployment
metadata:
  labels:
    run: hello-world
  name: hello-world
spec:
  containers:
  - image: pancaaa/hello-world:latest
    name: hello-docker
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}