apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      # targetPort: 8080
      NodePort: 80080

  # selector:
  #   app: hello-world
  # # type: ClusterIP

  # # type: LoadBalancer
  # # # externalIPs:
  # # # - 10.111.13.16
