apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8080
  selector:
    app: hello-world
  # type: ClusterIP

  type: LoadBalancer
  # externalIPs:
  # - 10.111.13.16
