apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello
  labels:
    app: hello-world
    role: rolling-update
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        role: rolling-update
    spec:
      containers:
        - name: hello-world
          image: pancaaa/springboot-app:development
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/data"
              name: hello-pd
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
      volumes:
        - name: hello-pd
          persistentVolumeClaim:
            claimName: pvc-apps-1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: hello
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30006
