apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
    role: rolling-update
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        role: rolling-update
    spec:
      containers:
      - name: hello-world
        image: pancaaa/springboot-app:development
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: "/data"
            name: hello-pd
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
      volumes:
      - name : hello-pd
        persistentVolumeClaim:
          claimName: pvc-apps-1



